name: Django CI

on:
  push:
    branches: [ "Actions" ]
  pull_request:
    branches: [ "Actions" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Ensure requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "django" > requirements.txt
          fi

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run migrations
        run: python manage.py migrate

      - name: Run API tests with coverage
        run: |
          coverage run manage.py test
          coverage report
